<ul>
John Snow Inc.   
John Snow, Inc., and its nonprofit affiliate JSI Research & Training Institute, Inc.,   
are public health research and consulting firms dedicated to improving the health of   
individuals and communities throughout the world.  
JSI builds local capacity to address critical health problems, collaborating with local  
partners to assist countries, governments, communities, families, and individuals to   
develop their skills and identify solutions that meet their public health needs. Through   
management assistance, research and evaluation, education, and training, JSI works to enable  
agencies and health professionals to provide appropriate services in an effective and   
compassionate manner.  
For more than 25 years, Boston-based JSI and its other affiliates, including World Education,  
Inc., JohnSnowBrasil and Instituto Promundo, have provided high-quality technical and   
managerial assistance to public health programs worldwide. JSI has implemented projects   
in 102 countries, and currently operates from seven U.S. and 44 international offices, with more   
than 375 U.S.-based staff, and 700 host country national field-based staff.  
</ul>


